### ISSUE TITLE
Logo image in header is too big for phones

### ISSUE THREAD

**Issue by josempaii** [beefsweater/VRLX.Website#30] opened 2021-07-25 21:30 UTC
Tested in Ecosia (firefox based browser) and chrome. In both same result
![Screenshot_20210725-232102](https://user-images.githubusercontent.com/83276661/126914031-77de6c77-18e9-44a9-9858-96ff261dcad5.png)

**Comment by tleylan** [comment] 2021-07-26 03:26
We can use the 3 issues we have outstanding as a learning experience. Right off the bat one doesn't assign the issue to someone before it has been discussed and then the person to assign it to is agreed upon. Who is responsible for fixing the issue depends largely upon how we decide to fix it. Not just this issue every issue. It could mean making a phone call or paying a fee or resizing and image or whatever.

**Comment by tleylan** [comment] 2021-07-26 03:30
Now this comment can be about this issue. The problem is clearly that the image is considerably larger than the original. Nobody bothered to check. So what was the motivation for changing the image we had? In other words what was the "issue" that we decided needed fixing? One typically sees a problem manifested and then requests it be changed. So if there was a misspelling or a link was incorrect an issue would be raised, it would be assigned (most probably to the person who generated the misspelling or entered the wrong link).

**Comment by tleylan** [comment] 2021-07-26 03:33
In this case (again depending upon what was wrong) I would say we either need to resize the image or simply restore the original one. I can't know which until I understand what was wrong. If we decide to resize it would be best if someone with experience using a professional-level image editor do it. Doesn't have to be done that way but it would be nice if we didn't change the resolution or type while adjusting the size.

**Comment by beefsweater** [comment] 2021-07-26 22:57
@josempaii is this issue still active or was it fixed in our recent updates? It appears to be fixed.

**Comment by josempaii** [comment] 2021-07-26 23:07
@beefsweater is partially fixed, the logo is not bugged any more but it look kind of weird(in phones) so I'll try to find a solution in the next few days.

**Comment by tleylan** [comment] 2021-07-26 23:19
It is always a good idea to talk about it. I may know what the issue is. Let me suggest that you don't actually change anything except maybe to experiment locally. Rather you might mention what you think the problem is and how you would go about fixing it.

**Comment by tleylan** [comment] 2021-07-28 21:32
completed the fix and uploaded to Glitch

**Closed as completed by tleylan** 2021-07-28 21:32 UTC
Labels: bug
